mydata = read.table("household_power_consumption.txt",header=TRUE,stringsAsFactors=F,sep=";")
data=subset(mydata,Date=="1/2/2007" | Date=="2/2/2007")
library(lubridate)
data$Date<-dmy(data$Date)
data$DateTime<-paste(data$Date,data$Time)
data$DateTime<-strptime(data$DateTime,format="%Y-%m-%d %H:%M:%S")
png("plot2.png")
plot(data$DateTime,data$Global_active_power,type="l",ylab="Global Active Power(kilowatts)",xlab="")
dev.off()
